services:
  nuxt-app:
    container_name: nuxt-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
    command: npm run dev -- --host 0.0.0.0 --port 3000
